{
 "title": "FastAPI Observability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(api_app_info,instance)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Type Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({service_name=\"poc-backend\"} | pattern `<datetime> <level> [<logger>] [<fileno>] [<_>=<trace_id> <_>=<span_id> <_>=<trace_sampled>] - <msg>` | level != \"\" |= \"$log_keyword\" [30m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "{service_name=\"poc-backend\"} | pattern `<datetime> <level> [<logger>] [<file_with_lineno>] [<_>=<trace_id> <_>=<span_id> <_>=<trace_sampled>] - <msg>` | line_format \"{{.datetime}}\\t{{.level}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Duration > 1s",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "filters": [
      {
       "id": "4bc5c50c",
       "operator": "=",
       "scope": "resource",
       "tag": "pod.name",
       "value": [ "poc-backend-1" ],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "1s",
       "valueType": "duration"
      },
      { "id": "3f4a402a", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"poc-backend\" && duration>1s}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "filters": [
      {
       "id": "4bc5c50c",
       "operator": "=",
       "scope": "resource",
       "tag": "pod.name",
       "value": [ "$pod" ],
       "valueType": "string"
      },
      { "id": "101a2f61", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"poc-backend\" && name!~\"/metrics\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Up time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_requests_total{instance=\"$instance\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_requests_total{instance=\"$instance\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_requests_duration_seconds_sum{instance=\"$instance\"} / api_requests_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_exceptions_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (api_responses_total{instance=\"$instance\", status_code=~\"2.*\", path!=\"/metrics\"}) / sum by(path) (api_responses_total{instance=\"$instance\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (api_responses_total{instance=\"$instance\", status_code=~\"5.*\", path!=\"/metrics\"}) / sum by(path) (api_responses_total{instance=\"$instance\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(api_requests_duration_seconds_bucket{instance=\"$instance\", path!=\"/metrics\"}[10m])) by(path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "api_requests_in_progress{instance=\"$instance\", path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(api_requests_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}